// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import DollarOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/DollarOutlined';
import GiftOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/GiftOutlined';
import ShoppingOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ShoppingOutlined';
import FireOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/FireOutlined';
import UserOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/UserOutlined';
import MobileOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/MobileOutlined';
import BarChartOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/BarChartOutlined';
import ToolOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/ToolOutlined';
import TrophyOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/TrophyOutlined';
import SettingOutlined from 'C:/Users/Administrator/.openclaw/workspace/playground-management-system/node_modules/@umijs/plugins/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { HomeOutlined, DollarOutlined, GiftOutlined, ShoppingOutlined, FireOutlined, UserOutlined, MobileOutlined, BarChartOutlined, ToolOutlined, TrophyOutlined, SettingOutlined };
